import{RED,PLAYER_RADIUS,RUN_TIME,PHASE_TIMES,phaseAt,phaseProgress,collides,finalSafe}from'./game-core.mjs';
const c=document.querySelector('#canvas'),x=c.getContext('2d'),$=s=>document.querySelector(s),ui={intro:$('#intro'),result:$('#result'),resultLabel:$('#resultLabel'),play:$('#play'),again:$('#again'),time:$('#time'),phase:$('#phase'),cue:$('#cue'),survived:$('#survived'),best:$('#best'),finalPhase:$('#finalPhase'),impact:$('#impact'),flash:$('#flash'),sound:$('#sound')};
let w=0,h=0,dpr=1,running=false,dead=false,qaRun=false,touchMode=false,start=0,last=0,t=0,shake=0,flash=0,qaGrace=0,transitionUntil=0,phaseFade=1,particles=[],trail=[],hazards=[],hunters=[],hunterClock=0,hunterCount=0,pointer={x:0,y:0,active:false},keys={},bgRed=0,best=+(localStorage.getItem('dtr-best-v2')||0),raf;const player={x:0,y:0,tx:0,ty:0,r:PLAYER_RADIUS};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,n)=>a+(b-a)*n,ease=n=>n*n*(3-2*n),rand=(a,b)=>a+Math.random()*(b-a);
class Sound{constructor(){this.on=true}start(){if(this.ctx)return;let A=window.AudioContext||window.webkitAudioContext;this.ctx=new A;this.master=this.ctx.createGain();this.master.gain.value=.18;this.master.connect(this.ctx.destination);this.next=0}tone(f,d=.1,v=.1,type='sine'){if(!this.ctx||!this.on)return;let o=this.ctx.createOscillator(),g=this.ctx.createGain(),n=this.ctx.currentTime;o.type=type;o.frequency.setValueAtTime(f,n);g.gain.setValueAtTime(v,n);g.gain.exponentialRampToValueAtTime(.001,n+d);o.connect(g).connect(this.master);o.start(n);o.stop(n+d)}beat(now,intense){if(!this.ctx||!this.on||now<this.next)return;this.next=now+(intense?.22:.42);this.tone(intense?78:58,.08,intense?.11:.06,'triangle')}}const sound=new Sound;
function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,2);c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';x.setTransform(dpr,0,0,dpr,0,0);if(!player.x)resetPlayer()}
function resetPlayer(){player.x=player.tx=w/2;player.y=player.ty=h*.72;pointer.x=player.x;pointer.y=player.y}
function startGame(){sound.start();running=true;dead=qaRun=false;shown=-1;t=hunterClock=hunterCount=0;start=performance.now();last=start;particles=[];trail=[];hunters=[];resetPlayer();ui.intro.classList.remove('open');ui.result.classList.remove('open');document.body.classList.add('playing');setCue(matchMedia('(pointer:coarse)').matches?'DRAG TO MOVE':'MOVE',matchMedia('(pointer:coarse)').matches?'White stays above your finger. Red ends the run.':'White follows you. Red ends the run.');c.focus()}
function setCue(a,b){ui.cue.innerHTML=`<b>${a}</b><span>${b}</span>`;ui.cue.style.opacity=1;clearTimeout(setCue.id);setCue.id=setTimeout(()=>ui.cue.style.opacity=0,3200)}
const phaseNames=[['ONE RULE','Avoid red. Everything else is harmless.'],['ORBIT','Read the rotation. Move early.'],['TRUST ISSUES','Neutral shapes warn before turning red.'],['READ BETWEEN','Only the red letters can hurt you.'],['TILT','The world moves. Your control does not.'],['THIN LINE','Stay loose. Corridors are temporary.'],['MULTIPLY','One becomes many. Watch the gaps.'],['THE WAVE','Move with the opening.'],['INVERSION','Red is everywhere. Stay inside the light.']];let shown=-1;
function hazard(kind,o){hazards.push({kind,red:true,...o})}
function spawnHunter(p){let edge=hunterCount++%4,x0,y0,margin=28;if(edge===0){x0=-margin;y0=clamp(player.ty,100,h-30)}if(edge===1){x0=w+margin;y0=clamp(player.ty,100,h-30)}if(edge===2){x0=clamp(player.tx,30,w-30);y0=78-margin}if(edge===3){x0=clamp(player.tx,30,w-30);y0=h+margin}let lead=.22+p*.025,aimX=clamp(player.tx+(player.tx-player.x)*lead,20,w-20),aimY=clamp(player.ty+(player.ty-player.y)*lead,90,h-20),a=Math.atan2(aimY-y0,aimX-x0),speed=125+p*12;hunters.push({x:x0,y:y0,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:11+p*.45,age:0,life:0,seeker:hunterCount%3===0})}
function updateHunters(dt,p){if(t<5)return;hunterClock-=dt;let interval=Math.max(1.55,3.4-p*.2),limit=2+Math.floor(p/3);if(hunterClock<=0&&hunters.length<limit){spawnHunter(p);hunterClock=interval}for(const q of hunters){q.age+=dt;q.life+=dt;if(q.seeker&&q.age>.55){let desired=Math.atan2(player.y-q.y,player.x-q.x),current=Math.atan2(q.vy,q.vx),diff=Math.atan2(Math.sin(desired-current),Math.cos(desired-current)),turn=clamp(diff,-.7*dt,.7*dt),speed=Math.hypot(q.vx,q.vy);q.vx=Math.cos(current+turn)*speed;q.vy=Math.sin(current+turn)*speed}if(q.age>.55){q.x+=q.vx*dt;q.y+=q.vy*dt}hazards.push({kind:'circle',x:q.x,y:q.y,r:q.r,red:q.age>.55,warn:q.age<=.55,hunter:true})}hunters=hunters.filter(q=>q.life<8&&q.x>-100&&q.x<w+100&&q.y>-100&&q.y<h+100)}
function buildScene(T){hazards=[];let p=phaseAt(T),u=phaseProgress(T),tt=T;bgRed=p===8?ease(u):0;
 if(p===0){for(let i=0;i<3;i++){let a=tt*(.55+i*.08)+i*2.1;hazard('circle',{x:w/2+Math.cos(a)*w*(.22+i*.08),y:h/2+Math.sin(a*1.23)*h*.27,r:18+i*4})}}
 if(p===1){for(let i=0;i<2;i++){let a=tt*(i?-.65:.5)+i*1.7,cx=w*(i?.68:.32),cy=h*.52,L=Math.min(w,h)*.34;hazard('segment',{x1:cx-Math.cos(a)*L,y1:cy-Math.sin(a)*L,x2:cx+Math.cos(a)*L,y2:cy+Math.sin(a)*L,width:13})}hazard('circle',{x:w/2,y:h/2,r:22})}
 if(p===2){for(let i=0;i<7;i++){let cycle=(u*2+i*.19)%1,red=cycle>.58,xp=(i+1)*w/8;hazards.push({kind:'circle',x:xp,y:h*.5+Math.sin(tt*1.2+i)*h*.23,r:16,red,warn:cycle>.46&&!red})}}
 if(p===3){let word='DANGER',size=Math.min(w/5.5,150),left=w/2-size*2.55;for(let i=0;i<6;i++){let yy=h/2+Math.sin(tt*1.5+i)*45;hazard('rect',{x:left+i*size*.88,y:yy-size*.5,w:size*.72,h:size,letter:word[i]})}}
 if(p===4){let cx=w/2,cy=h/2,a=tt*.28;for(let i=0;i<4;i++){let aa=a+i*Math.PI/2,L=Math.max(w,h)*.64;hazard('segment',{x1:cx+Math.cos(aa)*90,y1:cy+Math.sin(aa)*90,x2:cx+Math.cos(aa)*L,y2:cy+Math.sin(aa)*L,width:16})}}
 if(p===5){let gap=h*(.32-u*.12),cy=h/2+Math.sin(tt*.75)*h*.18;hazard('rect',{x:0,y:0,w:w,h:Math.max(0,cy-gap/2)});hazard('rect',{x:0,y:cy+gap/2,w:w,h:h-(cy+gap/2)});for(let i=0;i<3;i++)hazard('circle',{x:(tt*110+i*w/3)%w,y:cy+Math.sin(tt+i)*gap*.3,r:14})}
 if(p===6){for(let i=0;i<14;i++){let a=i*.9+tt*(i%2?.34:-.27),rad=60+(i%5)*52;hazard('circle',{x:w/2+Math.cos(a)*rad,y:h/2+Math.sin(a*1.07)*rad*.7,r:9+(i%3)*4})}}
 if(p===7){let wave=((u*1.35)%1.2)*w-w*.1,gapY=h*.24+((Math.sin(tt*.7)+1)/2)*h*.52;hazard('rect',{x:wave,y:0,w:Math.max(34,w*.085),h:Math.max(0,gapY-70)});hazard('rect',{x:wave,y:gapY+70,w:Math.max(34,w*.085),h:h-gapY-70});for(let i=0;i<5;i++)hazard('circle',{x:w*(.15+i*.18),y:h/2+Math.sin(tt*1.3+i)*h*.3,r:12})}
 let safe=null;if(p===8){safe={x:w/2+Math.sin(tt*.8)*w*.25,y:h/2+Math.cos(tt*1.12)*h*.22,r:Math.max(52,Math.min(w,h)*( .22-u*.09))}}
 return safe}
function move(dt){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(dx||dy){let m=Math.hypot(dx,dy);player.tx+=dx/m*430*dt;player.ty+=dy/m*430*dt}player.tx=clamp(player.tx,player.r,w-player.r);player.ty=clamp(player.ty,82,h-player.r);let follow=1-Math.pow(.0008,dt);player.x=lerp(player.x,player.tx,follow);player.y=lerp(player.y,player.ty,follow);trail.push({x:player.x,y:player.y,life:1});if(trail.length>24)trail.shift()}
function die(){if(dead)return;dead=true;running=false;shake=18;flash=1;sound.tone(52,.45,.35,'sawtooth');for(let i=0;i<70;i++)particles.push({x:player.x,y:player.y,vx:rand(-320,320),vy:rand(-320,320),life:rand(.5,1),red:i%3===0});ui.impact.classList.add('show');setTimeout(()=>{ui.impact.classList.remove('show');showResult()},180)}
function showResult(){let s=Math.min(t,RUN_TIME);if(!qaRun){best=Math.max(best,s);localStorage.setItem('dtr-best-v2',best.toFixed(1))}ui.survived.textContent=s.toFixed(1)+'s';ui.best.textContent=best.toFixed(1)+'s';ui.finalPhase.textContent=String(phaseAt(s)+1).padStart(2,'0');ui.resultLabel.textContent=s>=120?'SURVIVED':'CONTACT';ui.result.classList.add('open');document.body.classList.remove('playing')}
function update(dt,now){if(!running)return;t=Math.min(RUN_TIME,(now-start)/1000);let p=phaseAt(t);if(p!==shown){shown=p;transitionUntil=now+800;setCue(...phaseNames[p]);sound.tone(220+p*55,.35,.12)}phaseFade=clamp(1-(transitionUntil-now)/800,0,1);move(dt);let safe=buildScene(t);updateHunters(dt,p);let hit=collides(player,hazards);if(now>Math.max(qaGrace,transitionUntil)&&(hit||finalSafe(player,safe,p===8)))die();if(t>=RUN_TIME&&!dead){running=false;showResult()}sound.beat(now/1000,p>=6);ui.time.textContent=t.toFixed(1).padStart(5,'0');ui.phase.textContent=String(p+1).padStart(2,'0')+' / 09';return safe}
function drawShape(q){x.save();x.globalAlpha=q.hunter?1:phaseFade;x.fillStyle=q.red?RED:q.warn?'#202025':'#99999f';x.strokeStyle=q.red?'#ff7985':q.warn?'#f6f5f1':'#aaa';x.shadowColor=q.red?RED:'transparent';x.shadowBlur=q.red?18:0;if(q.kind==='circle'){x.beginPath();x.arc(q.x,q.y,q.r,0,7);q.red?x.fill():x.stroke()}else if(q.kind==='rect'){x.fillRect(q.x,q.y,q.w,q.h);if(q.letter){x.fillStyle='#08080a';x.font=`900 ${q.h*.72}px Arial`;x.textAlign='center';x.textBaseline='middle';x.fillText(q.letter,q.x+q.w/2,q.y+q.h/2)}}else{x.lineWidth=q.width;x.lineCap='round';x.beginPath();x.moveTo(q.x1,q.y1);x.lineTo(q.x2,q.y2);x.stroke()}x.restore()}
function draw(safe){x.setTransform(dpr,0,0,dpr,0,0);x.save();x.translate(rand(-shake,shake),rand(-shake,shake));x.fillStyle=bgRed?`rgb(${Math.floor(5+bgRed*245)},${Math.floor(5+bgRed*25)},${Math.floor(6+bgRed*34)})`:'#050506';x.fillRect(-30,-30,w+60,h+60);x.strokeStyle=bgRed?'#ff6873':'#17171b';x.lineWidth=1;for(let i=0;i<12;i++){x.beginPath();x.moveTo(0,(i+1)*h/13);x.lineTo(w,(i+1)*h/13);x.stroke()}hazards.forEach(drawShape);if(safe){x.save();x.globalCompositeOperation='destination-out';x.beginPath();x.arc(safe.x,safe.y,safe.r,0,7);x.fill();x.restore();x.strokeStyle='#fff';x.lineWidth=2;x.beginPath();x.arc(safe.x,safe.y,safe.r,0,7);x.stroke()}trail.forEach((p,i)=>{x.globalAlpha=p.life*i/trail.length*.3;x.fillStyle='#fff';x.beginPath();x.arc(p.x,p.y,player.r*(i/trail.length),0,7);x.fill();p.life*=.94});x.globalAlpha=1;if(pointer.active&&touchMode){x.strokeStyle='#ffffff30';x.lineWidth=1;x.setLineDash([3,5]);x.beginPath();x.moveTo(player.x,player.y);x.lineTo(pointer.x,pointer.y);x.stroke();x.setLineDash([]);x.strokeStyle='#ffffff66';x.beginPath();x.arc(pointer.x,pointer.y,12,0,7);x.stroke()}x.fillStyle='#fff';x.shadowColor='#fff';x.shadowBlur=22;x.beginPath();x.arc(player.x,player.y,player.r,0,7);x.fill();x.shadowBlur=0;particles.forEach(p=>{x.globalAlpha=p.life;x.fillStyle=p.red?RED:'#fff';x.fillRect(p.x,p.y,3,3);p.x+=p.vx/60;p.y+=p.vy/60;p.vx*=.96;p.vy*=.96;p.life-=.025});x.restore();shake*=.84;flash*=.8;ui.flash.style.opacity=flash}
function loop(now){let dt=Math.min(.033,(now-last)/1000||0);last=now;let safe=update(dt,now);draw(safe);raf=requestAnimationFrame(loop)}
function point(e){let p=e.touches?.[0]||e;touchMode=e.pointerType==='touch'||matchMedia('(pointer:coarse)').matches||innerWidth<=700;let offset=touchMode?clamp(h*.105,62,92):0;pointer.x=clamp(p.clientX,player.r,w-player.r);pointer.y=clamp(p.clientY,82,h-player.r);player.tx=pointer.x;player.ty=clamp(pointer.y-offset,82,h-player.r);pointer.active=true}function release(e){if(e.pointerType==='touch'||touchMode)pointer.active=false}c.addEventListener('pointermove',point);c.addEventListener('pointerdown',e=>{point(e);c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointerup',release);c.addEventListener('pointercancel',release);addEventListener('keydown',e=>{keys[e.key]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if(running&&['127.0.0.1','localhost'].includes(location.hostname)){let n=+e.key;if(n>=1&&n<=9){qaRun=true;start=performance.now()-PHASE_TIMES[n-1]*1000;qaGrace=performance.now()+500;player.x=player.tx=w/2;player.y=player.ty=h*.72}if(e.key==='q'){qaRun=true;start=performance.now()-119950;qaGrace=performance.now()+1000}if(e.key==='0'){qaRun=true;qaGrace=0;buildScene(t);let q=hazards.find(v=>v.red);if(q){player.x=player.tx=q.kind==='segment'?(q.x1+q.x2)/2:q.kind==='rect'?q.x+q.w/2:q.x;player.y=player.ty=q.kind==='segment'?(q.y1+q.y2)/2:q.kind==='rect'?q.y+q.h/2:q.y}}}});addEventListener('keyup',e=>keys[e.key]=false);addEventListener('resize',resize);ui.play.onclick=startGame;ui.again.onclick=startGame;ui.sound.onclick=()=>{sound.on=!sound.on;ui.sound.textContent=sound.on?'SOUND ◉':'SOUND ○'};resize();draw();raf=requestAnimationFrame(loop);
