const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),W=960,H=600;
const $=s=>document.querySelector(s),ui={round:$('#round'),levelName:$('#levelName'),goals:$('#goals'),shots:$('#shots'),score:$('#score'),power:$('#power'),shoot:$('#shoot'),callout:$('#callout'),result:$('#result'),select:$('#levelSelect')};
const goal={l:205,r:755,t:154,b:374};let aim,keeper,ball,attempts,points,streak,power,dir,state,start,shot,particles,net,sound=true,last=0;
const levels={1:{name:'TRAINING',save:.021,wind:0,target:false},2:{name:'MOVING KEEPER',save:.056,wind:0,target:false},3:{name:'WIND CHALLENGE',save:.129,wind:18,target:false},4:{name:'TARGET MASTER',save:.167,wind:0,target:true},5:{name:'CHAMPIONSHIP',save:.40,wind:28,target:true}};let level=1,wind=0,targetSide=0;
function chooseLevel(n){level=Number(n);$('#currentLevel').textContent=`LEVEL ${level} · ${levels[level].name}`;ui.select.classList.add('hidden');resetGame()}
function resetGame(){attempts=[];points=streak=0;particles=[];ui.result.classList.add('hidden');resetShot();updateUI()}
function resetShot(){aim={x:480,y:250};keeper={x:480,y:344,tx:480,ty:344};ball={x:480,y:530,r:19};power=.45;dir=1;wind=levels[level].wind?(Math.random()*.8+.2)*levels[level].wind*(Math.random()<.5?-1:1):0;targetSide=Math.random()<.5?0:1;state='aim';ui.shoot.disabled=false;say(level===1?'TRAINING SHOT':'AIM YOUR SHOT',level>=3?`Wind ${wind<0?'←':'→'} ${Math.abs(wind).toFixed(0)}`:'Move the glowing target')}
function updateUI(){ui.levelName.textContent=`LEVEL ${level} · ${levels[level].name}`;ui.round.textContent=`SHOT ${Math.min(attempts.length+1,5)} / 5`;ui.goals.textContent=attempts.filter(Boolean).length;ui.score.textContent=String(points).padStart(4,'0');ui.shots.innerHTML=Array.from({length:5},(_,i)=>`<i class="dot ${i<attempts.length?(attempts[i]?'goal':'miss'):''}"></i>`).join('')}
function say(a,b){ui.callout.innerHTML=`<strong>${a}</strong><span>${b}</span>`;ui.callout.classList.add('pop');setTimeout(()=>ui.callout.classList.remove('pop'),200)}
function tone(type){if(!sound)return;const ac=tone.ac||(tone.ac=new(window.AudioContext||window.webkitAudioContext)()),o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);o.type=type==='goal'?'sine':'triangle';o.frequency.setValueAtTime(type==='goal'?430:160,ac.currentTime);o.frequency.exponentialRampToValueAtTime(type==='goal'?920:70,ac.currentTime+.3);g.gain.setValueAtTime(.11,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.32);o.start();o.stop(ac.currentTime+.33)}
function stadium(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#071426');g.addColorStop(.45,'#173c59');g.addColorStop(.46,'#17653a');g.addColorStop(1,'#08723e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#08131f';ctx.fillRect(0,35,W,112);
 const colors=['#ffe25a','#f04b64','#3ad5ff','#f4f4f4','#64eb91'];for(let y=48;y<142;y+=12)for(let x=9;x<W;x+=14){ctx.globalAlpha=.3+(x*y%45)/100;ctx.fillStyle=colors[(x*17+y*31)%colors.length];ctx.beginPath();ctx.arc(x+(y%4),y,3,0,7);ctx.fill()}ctx.globalAlpha=1;
 [[70,25],[890,25]].forEach(([x,y])=>{g=ctx.createRadialGradient(x,y,4,x,y,120);g.addColorStop(0,'#fff');g.addColorStop(.09,'#b8edff99');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-130,y-20,260,230)});for(let i=0;i<5;i++){ctx.fillStyle=`rgba(255,255,255,${.035+i*.007})`;ctx.fillRect(0,410+i*37,W,18)}ctx.strokeStyle='#fff9';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,475);ctx.quadraticCurveTo(480,390,960,475);ctx.stroke();
 ctx.strokeStyle='#9cb9cb';ctx.lineWidth=3;ctx.strokeRect(goal.l+20,goal.t+18,goal.r-goal.l-40,goal.b-goal.t);ctx.save();ctx.globalAlpha=.55+net*.25;ctx.strokeStyle='#e4f8ff';ctx.lineWidth=1;for(let x=goal.l+20;x<=goal.r-20;x+=28){ctx.beginPath();ctx.moveTo(x,goal.t+18);ctx.lineTo(x+(x-480)*net*.025,goal.b);ctx.stroke()}for(let y=goal.t+18;y<=goal.b;y+=25){ctx.beginPath();ctx.moveTo(goal.l+20,y);ctx.lineTo(goal.r-20,y);ctx.stroke()}ctx.restore();ctx.strokeStyle='#fff';ctx.lineWidth=13;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(goal.l,goal.b);ctx.lineTo(goal.l,goal.t);ctx.lineTo(goal.r,goal.t);ctx.lineTo(goal.r,goal.b);ctx.stroke();
 (levels[level].target?[[goal.l+55,goal.t+50],[goal.r-55,goal.t+50]].filter((_,i)=>i===targetSide):[]).forEach(([x,y])=>{g=ctx.createRadialGradient(x,y,2,x,y,40);g.addColorStop(0,'#ffda3dcc');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,39,0,7);ctx.fill();ctx.strokeStyle='#ffe34e';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,22,0,7);ctx.stroke();ctx.fillStyle='#fff';ctx.font='800 12px Inter';ctx.textAlign='center';ctx.fillText('250',x,y+4)});if(level>=3){ctx.fillStyle='#071727dd';ctx.fillRect(790,16,150,38);ctx.fillStyle='#55d9ff';ctx.font='800 17px Barlow Condensed';ctx.textAlign='center';ctx.fillText(`WIND ${wind<0?'←':'→'} ${Math.abs(wind).toFixed(0)}`,865,41)}}
function drawKeeper(){const{x,y}=keeper,lean=(keeper.tx-x)*.018;ctx.save();ctx.translate(x,y);ctx.rotate(lean*.03);ctx.strokeStyle='#f8bd37';ctx.lineWidth=14;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-10,-55);ctx.lineTo(-53-lean,-24);ctx.moveTo(10,-55);ctx.lineTo(53+lean,-24);ctx.stroke();ctx.strokeStyle='#18253b';ctx.beginPath();ctx.moveTo(-13,-5);ctx.lineTo(-28,40);ctx.moveTo(13,-5);ctx.lineTo(28,40);ctx.stroke();ctx.fillStyle='#ffb92e';ctx.beginPath();ctx.roundRect(-29,-70,58,70,12);ctx.fill();ctx.fillStyle='#102541';ctx.font='900 30px Barlow Condensed';ctx.textAlign='center';ctx.fillText('1',0,-25);ctx.fillStyle='#efb08c';ctx.beginPath();ctx.arc(0,-88,18,0,7);ctx.fill();ctx.fillStyle='#402b24';ctx.beginPath();ctx.arc(0,-94,17,Math.PI,0);ctx.fill();ctx.restore()}
function drawAim(){if(state!=='aim')return;const p=1+Math.sin(performance.now()/120)*.12;ctx.save();ctx.translate(aim.x,aim.y);ctx.scale(p,p);ctx.strokeStyle='#45eaff';ctx.lineWidth=3;ctx.shadowColor='#45eaff';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(0,0,23,0,7);ctx.moveTo(-34,0);ctx.lineTo(-12,0);ctx.moveTo(34,0);ctx.lineTo(12,0);ctx.moveTo(0,-34);ctx.lineTo(0,-12);ctx.moveTo(0,34);ctx.lineTo(0,12);ctx.stroke();ctx.restore()}
function drawBall(){ctx.save();ctx.translate(ball.x,ball.y);ctx.rotate((ball.x+ball.y)/28);ctx.shadowColor='#000';ctx.shadowBlur=10;ctx.shadowOffsetY=7;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,0,ball.r,0,7);ctx.fill();ctx.fillStyle='#172236';for(let i=0;i<5;i++){let a=i*Math.PI*2/5;ctx.beginPath();ctx.arc(Math.cos(a)*ball.r*.55,Math.sin(a)*ball.r*.55,ball.r*.22,0,7);ctx.fill()}ctx.restore()}
function burst(x,y,color,n=45){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*8,vy:-Math.random()*8-2,life:1,color,s:3+Math.random()*5})}
function drawParticles(){particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.2;p.life-=.018;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.s,p.s)});ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0)}
function setAim(cx,cy){if(state!=='aim')return;const r=canvas.getBoundingClientRect();aim.x=Math.max(goal.l+28,Math.min(goal.r-28,(cx-r.left)*W/r.width));aim.y=Math.max(goal.t+30,Math.min(goal.b-25,(cy-r.top)*H/r.height))}
function takeShot(){if(state!=='aim')return;state='flight';ui.shoot.disabled=true;start=performance.now();const targetX=targetSide?goal.r-55:goal.l+55,error=Math.abs(power-.77),target={x:aim.x+(Math.random()-.5)*error*95+wind,y:aim.y+(Math.random()-.5)*error*55},corner=levels[level].target&&Math.hypot(target.x-targetX,target.y-(goal.t+50))<48,perfect=error<.075;let saveChance=levels[level].save+(error>.25?.06:0)-(perfect?.025:0)-(corner?.02:0);saveChance=Math.max(.005,Math.min(.7,saveChance));const saved=level===1?Math.hypot(target.x-480,target.y-285)<70&&Math.random()<.25:Math.random()<saveChance;if(level===1){keeper.tx=480;keeper.ty=344}else if(saved){keeper.tx=target.x;keeper.ty=target.y+35}else{keeper.tx=target.x+(Math.random()<.5?-1:1)*(105+Math.random()*100);keeper.ty=target.y+35}shot={sx:ball.x,sy:ball.y,target,goal:!saved,corner,perfect};tone('kick')}
function finish(){attempts.push(shot.goal);if(shot.goal){streak++;let won=100+(shot.corner?250:0)+(shot.perfect?75:0)+(streak-1)*25;points+=won;say(shot.corner?'TOP CORNER!':shot.perfect?'PERFECT STRIKE!':'GOOOAL!',`+${won} points`);burst(shot.target.x,shot.target.y,'#ffdb3c',65);net=1;tone('goal')}else{streak=0;say('SAVED!','The keeper read your shot');burst(shot.target.x,shot.target.y,'#55d6ff',28);tone('save')}updateUI();state='pause';setTimeout(attempts.length===5?results:resetShot,1500)}
function results(){state='done';let n=attempts.filter(Boolean).length,title,text;if(level===5&&n===5){title='PERFECT CHAMPION!';text='The rare 5/5 final! You have conquered the championship!'}else if(n===5){title='LEVEL MASTERED!';text='Five unstoppable strikes. Ready for the next challenge!'}else if(n>=3){title=level===5?'CHAMPION!':'LEVEL PASSED!';text=level===5?'Three goals under maximum pressure—you win the cup!':'Strong finishing. Take on the next level!'}else{title='TRY AGAIN!';text='Every champion practises. Watch, aim, and pick your moment!'}$('#resultTitle').textContent=title;$('#resultText').textContent=text;$('#finalGoals').textContent=`${n}/5`;$('#finalScore').textContent=points;$('#next').style.display=level<5&&n>=3?'block':'none';ui.result.classList.remove('hidden');burst(480,220,'#ffdb3c',n>=3?120:35)}
function frame(now){let dt=Math.min(32,now-last||16);last=now;if(state==='aim'){power+=dir*dt*.00065;if(power>=1||power<=.12){dir*=-1;power=Math.max(.12,Math.min(1,power))}if(level>=2)keeper.x=480+Math.sin(now/(level===5?430:700))*(level===5?155:115)}if(state==='flight'){let t=Math.min(1,(now-start)/780),e=1-Math.pow(1-t,3);ball.x=shot.sx+(shot.target.x-shot.sx)*e;ball.y=shot.sy+(shot.target.y-shot.sy)*e-Math.sin(Math.PI*t)*85;ball.r=19-8*e;keeper.x+=(keeper.tx-keeper.x)*.105;keeper.y+=(keeper.ty-keeper.y)*.08;if(t===1){state='resolve';finish()}}net*=.94;ui.power.style.width=`${power*100}%`;stadium();drawKeeper();drawAim();drawBall();drawParticles();requestAnimationFrame(frame)}
canvas.addEventListener('pointermove',e=>setAim(e.clientX,e.clientY));canvas.addEventListener('pointerdown',e=>setAim(e.clientX,e.clientY));ui.shoot.addEventListener('click',takeShot);$('#again').addEventListener('click',resetGame);$('#next').addEventListener('click',()=>chooseLevel(Math.min(5,level+1)));$('#levelsBtn').addEventListener('click',()=>{state='menu';ui.result.classList.add('hidden');ui.select.classList.remove('hidden')});document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>chooseLevel(b.dataset.level)));$('#sound').addEventListener('click',e=>{sound=!sound;e.currentTarget.textContent=sound?'🔊':'🔇'});addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key===' ')takeShot();if(state==='aim'){if(e.key==='ArrowLeft')aim.x-=14;if(e.key==='ArrowRight')aim.x+=14;if(e.key==='ArrowUp')aim.y-=12;if(e.key==='ArrowDown')aim.y+=12;aim.x=Math.max(goal.l+28,Math.min(goal.r-28,aim.x));aim.y=Math.max(goal.t+30,Math.min(goal.b-25,aim.y))}});
resetGame();requestAnimationFrame(frame);
