"use strict";
const canvas=document.getElementById("raceCanvas"),ctx=canvas.getContext("2d"),$=id=>document.getElementById(id);
const ui={position:$("position"),leg:$("leg"),speed:$("speed"),time:$("time"),direction:$("direction"),boost:$("boostBar"),progress:$("progressBar"),progressCar:$("progressCar"),countdown:$("countdown"),message:$("message"),start:$("startPanel"),finish:$("finishPanel"),best:$("bestTime"),finalPosition:$("finalPosition"),finalTime:$("finalTime"),finishTitle:$("finishTitle"),medal:$("medal"),sound:$("soundButton")};
const W=520,H=720,ROAD_L=75,ROAD_R=445,LANES=[121,214,306,399],LEG=20000,TOTAL=LEG;
const keys={left:false,right:false,gas:false,brake:false,turbo:false},RIVAL_SPEEDS={level1:[.73,.77,.81],level2:[1.1,1.16,1.22],level3:[1.21,1.26,1.3]};
let state,previous=0,raf,audio,soundOn=true,messageTimer;
const ordinal=n=>n===1?"1st":n===2?"2nd":n===3?"3rd":"4th",format=s=>`${Math.floor(s/60)}:${(s%60).toFixed(1).padStart(4,"0")}`;
function fresh(){return{running:false,paused:false,counting:true,countClock:0,count:3,time:0,level:"level1",leg:1,direction:1,road:0,boost:100,boosting:false,finishers:[],player:{lane:1,x:LANES[1],targetX:LANES[1],y:570,speed:0,distance:0,finished:false,place:0,hit:0},rivals:[],objects:[],particles:[]}}
state=fresh();
function tone(f,d,type="sine",v=.07){if(!soundOn)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(_){}}
function spawnRivals(){state.rivals=RIVAL_SPEEDS[state.level].map((factor,i)=>{const lane=i+(i>=1?1:0);return{lane,targetLane:lane,x:LANES[lane],distance:-45-i*34,speed:factor,color:["#ee4f62","#f3a51f","#735dcc"][i],finished:false,place:0,canChange:state.level==="level3"&&i<2,change:2.5+i,warning:0}})}
function makeLegObjects(){state.objects=[];if(state.level!=="level3"){for(let d=1300;d<LEG-600;d+=1700+Math.random()*700){const lane=Math.floor(Math.random()*4);state.objects.push({type:"boost",lane,x:LANES[lane],distance:d,hit:false})}return}for(let d=900;d<LEG-500;d+=900+Math.random()*550){const safe=Math.floor(Math.random()*4),blocked=[0,1,2,3].filter(l=>l!==safe).sort(()=>Math.random()-.5).slice(0,Math.random()<.45?2:1);blocked.forEach((lane,i)=>state.objects.push({type:i===0&&Math.random()<.42?"oil":"cone",lane,x:LANES[lane],distance:d,hit:false}));if(Math.random()<.58)state.objects.push({type:"boost",lane:safe,x:LANES[safe],distance:d+35,hit:false})}}
function drawRoad(){ctx.fillStyle="#e9b96d";ctx.fillRect(0,0,W,H);for(let y=-90+(state.road*.28)%150;y<H;y+=150){ctx.fillStyle="#d58e45";ctx.beginPath();ctx.moveTo(0,y+55);ctx.lineTo(62,y);ctx.lineTo(62,y+78);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(W,y+100);ctx.lineTo(458,y+35);ctx.lineTo(458,y+120);ctx.closePath();ctx.fill();ctx.fillStyle="#23896f";ctx.fillRect(25,y+69,8,42);ctx.fillRect(16,y+78,26,8);ctx.fillRect(487,y+27,8,45);ctx.fillRect(477,y+38,26,8)}ctx.fillStyle="#f7e5bd";ctx.fillRect(ROAD_L-14,0,14,H);ctx.fillRect(ROAD_R,0,14,H);ctx.fillStyle="#3e83a1";for(let y=-50+state.road%100;y<H;y+=100){ctx.fillRect(ROAD_L-14,y,14,50);ctx.fillRect(ROAD_R,y,14,50)}ctx.fillStyle="#514d50";ctx.fillRect(ROAD_L,0,ROAD_R-ROAD_L,H);ctx.fillStyle="#ffffff12";ctx.fillRect(ROAD_L+8,0,10,H);ctx.fillRect(ROAD_R-18,0,10,H);ctx.fillStyle="#f4c84b";for(const x of [168,260,352])for(let y=-100+state.road%150;y<H;y+=150)ctx.fillRect(x-3,y,6,80)}
function rounded(x,y,w,h,r,color){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=color;ctx.fill()}
function drawCar(x,y,color,player=false,flip=false,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);if(flip)ctx.rotate(Math.PI);ctx.fillStyle="#080b11";ctx.fillRect(-24,-34,9,19);ctx.fillRect(15,-34,9,19);ctx.fillRect(-24,15,9,19);ctx.fillRect(15,15,9,19);rounded(-21,-38,42,76,10,color);ctx.fillStyle="#b9e5f4";ctx.beginPath();ctx.moveTo(-15,-12);ctx.lineTo(-11,-27);ctx.lineTo(11,-27);ctx.lineTo(15,-12);ctx.closePath();ctx.fill();rounded(-15,-3,30,24,4,"#263a53");ctx.fillStyle="#fff7a4";ctx.fillRect(-15,-34,9,5);ctx.fillRect(6,-34,9,5);ctx.fillStyle="#ff263f";ctx.fillRect(-15,29,9,5);ctx.fillRect(6,29,9,5);if(player){ctx.fillStyle="#fff";ctx.fillRect(-3,-37,6,74)}ctx.restore()}
function screenY(distance){const delta=distance-state.player.distance,base=state.direction===1?570:150;return base-state.direction*delta*.42}
function drawObjects(){for(const o of state.objects){if(o.hit)continue;const y=screenY(o.distance);if(y<-50||y>H+50)continue;if(o.type==="boost"){ctx.fillStyle="#ffd72e";ctx.shadowColor="#ffec60";ctx.shadowBlur=12;rounded(o.x-29,y-17,58,34,5,"#ffd72e");ctx.shadowBlur=0;ctx.fillStyle="#1a1e29";ctx.font="bold 20px system-ui";ctx.textAlign="center";ctx.fillText("⚡",o.x,y+7)}else if(o.type==="cone"){ctx.fillStyle="#ff762e";ctx.beginPath();ctx.moveTo(o.x,y-20);ctx.lineTo(o.x-15,y+18);ctx.lineTo(o.x+15,y+18);ctx.closePath();ctx.fill();ctx.fillStyle="#fff";ctx.fillRect(o.x-10,y+1,20,6)}else{ctx.fillStyle="#151820";ctx.beginPath();ctx.ellipse(o.x,y,25,15,.2,0,Math.PI*2);ctx.fill();ctx.fillStyle="#252936";ctx.beginPath();ctx.ellipse(o.x-5,y-3,8,4,.2,0,Math.PI*2);ctx.fill()}}}
function drawFinish(){const next=state.leg*LEG,y=screenY(next);if(y>-40&&y<H+40)for(let i=0;i<20;i++)for(let j=0;j<2;j++){ctx.fillStyle=(i+j)%2?"#111":"#fff";ctx.fillRect(ROAD_L+i*18.5,y-18+j*18,18.5,18)}}
function updatePlayer(dt){const p=state.player;if(keys.left&&p.lane>0){p.lane--;p.targetX=LANES[p.lane];keys.left=false}if(keys.right&&p.lane<3){p.lane++;p.targetX=LANES[p.lane];keys.right=false}p.x+=(p.targetX-p.x)*Math.min(1,dt*9);let max=285;if(keys.turbo&&state.boost>0){state.boosting=true;max=355;state.boost=Math.max(0,state.boost-dt*25)}else{state.boosting=false;if(state.level!=="level3")state.boost=Math.min(100,state.boost+dt*7)}if(keys.gas)p.speed+=185*dt;else p.speed-=38*dt;if(keys.brake)p.speed-=210*dt;p.speed=Math.max(0,Math.min(max,p.speed));if(p.hit>0){p.hit-=dt;p.speed=Math.min(p.speed,135)}p.distance+=p.speed*dt;state.road+=p.speed*dt;collisions();if(p.distance>=TOTAL)finish(p,true)}
function updateRivals(dt){for(const r of state.rivals){if(r.finished)continue;let velocity=225*r.speed;const gap=state.player.distance-r.distance;if(state.level==="level2"){if(gap>120)velocity+=Math.min(80,(gap-120)*.3);if(gap<-120)velocity-=Math.min(65,(-gap-120)*.25)}if(state.level==="level3"){if(gap>300)velocity+=Math.min(24,(gap-300)*.08);if(gap<-300)velocity-=Math.min(12,(-gap-300)*.04);if(state.player.distance>TOTAL*.72)velocity+=9;if(r.canChange){if(r.warning>0){r.warning-=dt;if(r.warning<=0)r.lane=r.targetLane}else{r.change-=dt;if(r.change<=0){const choices=[r.lane-1,r.lane+1].filter(l=>l>=0&&l<4);r.targetLane=choices[Math.floor(Math.random()*choices.length)];r.warning=.7;r.change=2.8+Math.random()*2.8}}r.x+=(LANES[r.lane]-r.x)*Math.min(1,dt*4.5)}}r.distance+=velocity*dt;if(r.distance>=TOTAL)finish(r,false)}}
function collisions(){const p=state.player;for(const r of state.rivals){const y=screenY(r.distance);if(Math.abs(p.x-r.x)<37&&Math.abs(p.y-y)<67&&p.hit<=0){p.hit=.7;p.speed*=.65;burst(p.x,(p.y+y)/2,"#fff",7);notify("BUMP!");tone(110,.12,"square")}}for(const o of state.objects){if(o.hit||o.lane!==p.lane||Math.abs(o.distance-p.distance)>38)continue;o.hit=true;if(o.type==="boost"){state.boost=100;p.speed=Math.max(p.speed,285);notify("FULL TURBO!");tone(780,.18,"square")}else{p.hit=o.type==="oil"?1.1:.65;p.speed*=o.type==="oil"?.48:.62;notify(o.type==="oil"?"SLIPPERY OIL!":"CONE HIT!");tone(120,.18,"sawtooth")}}}
function finish(car,isPlayer){if(car.finished)return;car.finished=true;state.finishers.push(car);car.place=state.finishers.length;if(isPlayer)setTimeout(showFinish,500)}
function update(dt){if(!state.running||state.paused)return;if(state.counting){state.countClock+=dt;const n=3-Math.floor(state.countClock);if(n!==state.count&&n>=0){state.count=n;showCount(n===0?"GO!":String(n));tone(n===0?700:330,n===0?.22:.1,n===0?"square":"sine")}if(state.countClock>=4){state.counting=false;ui.countdown.classList.remove("show")}return}state.time+=dt;updatePlayer(dt);updateRivals(dt);for(const q of state.particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt}state.particles=state.particles.filter(q=>q.life>0);updateUI()}
function position(){return 1+state.rivals.filter(r=>r.distance>state.player.distance).length}
function updateUI(){ui.position.textContent=ordinal(state.player.finished?state.player.place:position());ui.leg.textContent="1";ui.speed.textContent=Math.round(state.player.speed*1.18);ui.time.textContent=format(state.time);ui.direction.textContent=state.level==="level3"?"🏆 LEVEL 3 · CHAMPION":state.level==="level2"?"🔥 LEVEL 2 · CLOSE RACE":"⭐ LEVEL 1 · EASY RACE";ui.boost.style.width=`${state.boost}%`;const pct=Math.min(100,state.player.distance/TOTAL*100);ui.progress.style.height=`${pct}%`;ui.progressCar.style.bottom=`${pct}%`;ui.progressCar.style.transform="translate(-50%,50%) rotate(-90deg)"}
function burst(x,y,color,n){for(let i=0;i<n;i++)state.particles.push({x,y,color,vx:(Math.random()-.5)*130,vy:(Math.random()-.5)*130,life:.45,size:2+Math.random()*4})}
function notify(text){clearTimeout(messageTimer);ui.message.textContent=text;ui.message.classList.add("show");messageTimer=setTimeout(()=>ui.message.classList.remove("show"),900)}
function showCount(text){ui.countdown.textContent=text;ui.countdown.classList.remove("show");void ui.countdown.offsetWidth;ui.countdown.classList.add("show")}
function draw(){drawRoad();drawObjects();drawFinish();for(const r of state.rivals){const y=screenY(r.distance);if(y>-80&&y<H+80){drawCar(r.x,y,r.color);if(r.warning>0){ctx.fillStyle="#ffea3d";ctx.font="bold 26px system-ui";ctx.textAlign="center";ctx.fillText(r.targetLane<r.lane?"◀":"▶",r.x,y-52)}}}const p=state.player;drawCar(p.x,p.y,"#159cff",true,false,p.hit>0&&Math.floor(p.hit*12)%2?0.35:1);if(state.boosting){ctx.fillStyle="#31ddff";for(let i=0;i<4;i++)ctx.fillRect(p.x+(i%2?12:-16),p.y+43+Math.random()*16,5,18)}for(const q of state.particles){ctx.globalAlpha=Math.min(1,q.life*3);ctx.fillStyle=q.color;ctx.fillRect(q.x,q.y,q.size,q.size);ctx.globalAlpha=1}if(state.paused){ctx.fillStyle="#050914bb";ctx.fillRect(0,0,W,H);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="italic 52px Impact";ctx.fillText("PAUSED",W/2,H/2)}}
function frame(now){const dt=Math.min(.033,(now-previous)/1000||0);previous=now;update(dt);draw();raf=requestAnimationFrame(frame)}
function startRace(){state=fresh();state.level=document.querySelector('input[name="level"]:checked').value;if(state.level==="level3")state.boost=45;spawnRivals();makeLegObjects();state.running=true;ui.start.classList.remove("open");ui.finish.classList.remove("open");previous=performance.now();updateUI();showCount("3");tone(330,.1)}
function showFinish(){state.running=false;const pos=state.player.place;ui.finalPosition.textContent=ordinal(pos);ui.finalTime.textContent=format(state.time);ui.finishTitle.textContent=pos===1?"CHAMPION!":pos===2?"PHOTO FINISH!":"GREAT RACE!";ui.medal.textContent=pos===1?"🏆":pos===2?"🥈":"🏁";const key=`highwayBest-${state.level}`,best=Number(localStorage.getItem(key)||0);if(!best||state.time<best)localStorage.setItem(key,state.time);refreshBest();ui.finish.classList.add("open");tone(pos===1?780:520,.3,"square")}
function refreshBest(){const level=document.querySelector('input[name="level"]:checked').value,best=Number(localStorage.getItem(`highwayBest-${level}`)||0);ui.best.textContent=best?format(best):"--:--.-"}
function bind(button,key,hold=false){button.addEventListener("pointerdown",e=>{e.preventDefault();keys[key]=true;button.classList.add("pressed")});for(const ev of ["pointerup","pointercancel","pointerleave"])button.addEventListener(ev,()=>{if(hold||key==="left"||key==="right")keys[key]=false;button.classList.remove("pressed")})}
bind($("leftButton"),"left");bind($("rightButton"),"right");bind($("gasButton"),"gas",true);bind($("brakeButton"),"brake",true);bind($("turboButton"),"turbo",true);
window.addEventListener("keydown",e=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","Space"].includes(e.code))e.preventDefault();if((e.code==="ArrowLeft"||e.code==="KeyA")&&!e.repeat)keys.left=true;if((e.code==="ArrowRight"||e.code==="KeyD")&&!e.repeat)keys.right=true;if(e.code==="ArrowUp"||e.code==="KeyW")keys.gas=true;if(e.code==="ArrowDown"||e.code==="KeyS")keys.brake=true;if(e.code==="Space")keys.turbo=true;if(e.code==="KeyP"&&state.running)state.paused=!state.paused});
window.addEventListener("keyup",e=>{if(e.code==="ArrowLeft"||e.code==="KeyA")keys.left=false;if(e.code==="ArrowRight"||e.code==="KeyD")keys.right=false;if(e.code==="ArrowUp"||e.code==="KeyW")keys.gas=false;if(e.code==="ArrowDown"||e.code==="KeyS")keys.brake=false;if(e.code==="Space")keys.turbo=false});window.addEventListener("blur",()=>{Object.keys(keys).forEach(k=>keys[k]=false);if(state.running)state.paused=true});
$("startButton").addEventListener("click",startRace);$("againButton").addEventListener("click",startRace);document.querySelectorAll('input[name="level"]').forEach(r=>r.addEventListener("change",refreshBest));ui.sound.addEventListener("click",()=>{soundOn=!soundOn;ui.sound.textContent=soundOn?"🔊":"🔇";ui.sound.setAttribute("aria-label",soundOn?"Turn sound off":"Turn sound on");if(soundOn)tone(540,.1)});refreshBest();updateUI();draw();raf=requestAnimationFrame(frame);
